# Generated by Django 3.1 on 2023-06-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20230601_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='is_favorite',
            new_name='is_starred',
        ),
    ]
