# Generated by Django 3.1 on 2023-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_count', models.PositiveIntegerField(default=0)),
                ('images_count', models.PositiveIntegerField(default=0)),
                ('music_count', models.PositiveIntegerField(default=0)),
                ('videos_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
