# Generated by Django 3.1 on 2023-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='documents_count',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='images_count',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='music_count',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='videos_count',
        ),
        migrations.AddField(
            model_name='storage',
            name='documents_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='images_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='music_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='videos_percentage',
            field=models.FloatField(default=0),
        ),
    ]
