# Generated by Django 3.1 on 2023-06-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
