# Generated by Django 3.1 on 2023-06-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starred', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starred',
            name='user',
        ),
    ]
