# Generated by Django 3.1 on 2023-06-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('starred', '0002_remove_starred_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starred',
            name='document',
        ),
        migrations.RemoveField(
            model_name='starred',
            name='image',
        ),
        migrations.RemoveField(
            model_name='starred',
            name='music',
        ),
        migrations.RemoveField(
            model_name='starred',
            name='video',
        ),
        migrations.AddField(
            model_name='starred',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='starred',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
