# Generated by Django 3.1 on 2023-06-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20230610_1842'),
        ('starred', '0003_auto_20230610_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        migrations.DeleteModel(
            name='Starred',
        ),
    ]
