# Generated by Django 3.1 on 2023-06-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starred', '0004_auto_20230613_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_starred', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='StarredDocument',
        ),
    ]
