# Generated by Django 3.1 on 2023-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20230601_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
