# Generated by Django 3.1 on 2023-06-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20230606_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_favorite',
            new_name='is_starred',
        ),
    ]
