# Generated by Django 3.1 on 2023-06-15 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20230610_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
