# Generated by Django 3.1 on 2023-06-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_uuid_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uuid_field',
        ),
    ]
