# Generated by Django 3.1 on 2023-06-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20230601_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='is_favorite',
            new_name='is_starred',
        ),
    ]
